source/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, RecruiterSignUpView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, StudentSignUpView,RecruiterProfileView
)

from django.conf.urls import url
from .views import (
    StudentProfileView, AutocompleteMajor, AutocompleteUni, AutocompleteCareerInt
)
app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('recruiter-sign-up/', RecruiterSignUpView.as_view(), name='recruiter_sign_up'),
    path('student-sign-up/', StudentSignUpView.as_view(), name='student_sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),
    

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),

    path('student-profile', StudentProfileView.as_view(), name='student_profile'),
    path('recruiter-profile', RecruiterProfileView.as_view(), name='recruiter_profile'),
    url(r'^major-autocomplete/$', AutocompleteMajor.as_view(), name='major-autocomplete'),
    url(r'^uni-autocomplete/$', AutocompleteUni.as_view(), name='uni-autocomplete'),
    url(r'^career-autocomplete/$', AutocompleteCareerInt.as_view(), name='career-autocomplete'),

    # path('', AccountSettings.as_view(), name='account_settings'),
]

source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('event/', include('event.urls')),
    path('profile/', include('user_profile.urls')),
    path('calendar/', include('calendars.urls')),
    path('career_fair/', include('career_fair.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/calendars/urls.py
from django.urls import path

from .views import (
    ViewCalendar,
)

app_name = "calendars"


urlpatterns = [
    path('', ViewCalendar.as_view(), name='view_calendar'),

]

source/event/urls.py
from django.urls import path
from django.conf.urls import url, include

from .views import (
    ViewEvent,
    EventList,
    MyEventList,
    CreateEvent,
    EventDashboard,
    detail,
    rsvp,
    un_rsvp,
    delete_event,
    PastEventList
    )

app_name = "event"


urlpatterns = [
    path('', EventDashboard.as_view(), name='event_dashboard'),
    path('event_list/', EventList.as_view(), name='event_list'),
    path('my_event_list/', MyEventList.as_view(), name='my_event_list'),
    url(r'^rsvp/(?P<event_id>[0-9]+)/$', rsvp, name='rsvp'),
    url(r'^un_rsvp/(?P<event_id>[0-9]+)/$', un_rsvp, name='un_rsvp'),
    url(r'^delete_event/(?P<event_id>[0-9]+)/$', delete_event, name='delete_event'),
    path('create_event', CreateEvent.as_view(), name ='create_event'),
    url(r'^(?P<event_id>[0-9]+)/$', detail, name='detail'),
    path('past_event/', PastEventList.as_view(), name='past_event'),
]

source/search/urls.py
from django.urls import path

from .views import (
    # RunSearch,
    run_search,
    # filters,

)

app_name = "search"


urlpatterns = [
    # path('', RunSearch.as_view(), name='run_search'),
    path('', run_search, name='run_search'),
    # path('', filters, name='filters'),
]

source/content/templates/layouts/default/account_settings.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Simple Django Login and Registration</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}




                
            {% else %}
            <div class="btn-group">
              <a href="{% url 'accounts:log_in' %}" class="btn btn-primary" role="button">Log in</a>
              <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   Create an account
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'accounts:sign_up' %}">Student</a>
                    <a class="dropdown-item" href="#">Recruiter</a>
                  </div>
                </div>
            </div>

                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                </li>
                <div class="dropdown">
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Create an account
                  </button> -->
                  
<!--                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li> -->
            {% endif %}
        </ul>


        <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Change language' %}</a>
                </li>
            </ul>
    </div>

</nav>

<div class = "search">
    <form class="example" action="{% url 'search:run_search' %}" >
            <input type="text" placeholder="Search.." name="search">
            <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}
    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

source/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title> Virtual Career Fair</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">  
    
    {% block css %} {% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">
        <!-- <i class="fa fa-home" aria-hidden="true"></i> -->
        {% trans ' Home' %}
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <div class ="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-cog fa-spin" aria-hidden="true"></i>
                        Settings
                    </button> 
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                        {% if request.user.is_recruiter %}
                            <a class="dropdown-item" href="{% url 'accounts:recruiter_profile' %}">{% trans 'Update profile' %}</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:student_profile' %}">{% trans 'Update profile' %}</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                        <a class="dropdown-item" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>

                    </div>
                </div>

         <!--        <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:view_profile' %}">{% trans 'Profile' %}</a>
                </li> -->

                <li class="nav-item">
                        <a class="nav-link" href="{% url 'calendars:view_calendar' %}">
                            <!-- <i class="fa fa-calendar" aria-hidden="true"></i> -->
                            {% trans ' Calendar' %}
                        </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'event:event_dashboard' %}">
                            <!-- <i class="fa fa-info-circle" aria-hidden="true"></i> -->
                            {% trans ' Infosessions' %}
                        </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'career_fair:career_fair_dashboard' %}">{% trans 'Career Fair' %}</a>
                </li>



                
            {% else %}
            <div class="btn-group">
              <a href="{% url 'accounts:log_in' %}" class="btn btn-primary" role="button">Log in</a>
              <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   Create an account
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'accounts:student_sign_up' %}">Student</a>
                    <a class="dropdown-item" href="{% url 'accounts:recruiter_sign_up' %}">Recruiter</a>
                  </div>
                </div>
            </div>
            {% endif %}
        </ul>


        <ul class="navbar-nav">
            <li>
                <div class = "search">
                    <form class="example" action="{% url 'search:run_search' %}" >
                        {% csrf_token %}
                        <input type="text" placeholder="Search.." name="keyword">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'change_language' %}">
                    {% trans 'Change language' %}
                    <i class="fa fa-language" aria-hidden="true"></i>
                </a>
            </li>

        </ul>
    </div>

</nav>


<div class="container-fluid mt-3">

    {% bootstrap_messages %}
    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

{% block javascripts %}{% endblock %}

</body>
</html>
{% block footer %}
{% endblock %}