source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('event/', include('event.urls')),
    path('profile/', include('user_profile.urls')),
    path('calendar/', include('calendars.urls')),
    path('career_fair/', include('career_fair.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/career_fair/urls.py
from django.urls import path
from django.conf.urls import url

from .views import (
    CareerFairDashboard,
    AutocompleteUni,
    CreateBooth,
    detail,
    BoothError,
    booth_detail,
    signup,
    remove,
    change,
    DeleteBoothConfirmation,
    DeleteBooth
)

app_name = "career_fair"


urlpatterns = [
    path('', CareerFairDashboard.as_view(), name='career_fair_dashboard'),
    url(r'^uni-autocomplete/$', AutocompleteUni.as_view(), name='uni-autocomplete'),
    path('create_booth', CreateBooth.as_view(), name = 'create-booth'),
    url(r'^(?P<event_id>[0-9]+)/$', detail, name='detail'),
    path('error', BoothError.as_view(), name = 'error'),
    url(r'^(?P<event_id>[0-9]+)/details/(?P<booth_company>[\w\-]+)/$', booth_detail, name='booth_detail'),
    url(r'^signup/(?P<slot_id>[0-9]+)/$', signup, name='signup'),
    url(r'^remove/(?P<slot_id>[0-9]+)/$', remove, name='remove'),
    url(r'^change/(?P<slot_id>[0-9]+)/$', change, name='change'),
    url(r'^delete_booth_confirmation/(?P<booth_id>[0-9]+)/$', DeleteBoothConfirmation.as_view(), name = 'delete_booth_confirmation'),
    url(r'^delete_booth/(?P<booth_id>\d+)/$', DeleteBooth, name='delete_booth')
]

source/career_fair/models.py
from django.db import models
from accounts.models import CustomUser


class Career_Fair(models.Model):
    """Model representing a career_fair."""
    university = models.CharField(max_length=100)
    firstdate = models.DateField(null=True, blank=True)
    lastdate = models.DateField(null = True, blank = True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.university}, {self.firstdate}, {self.lastdate}' 
        
class Career_Booth(models.Model):
	""" Model representing a booth in a career fair"""
	company = models.CharField(max_length=200)
	recruiter = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank = True)
	join_zoom_url = models.CharField(max_length=1000)
	start_zoom_url = models.CharField(max_length=1000)

	INTERVIEW_DURATION = (
	(4,'Four minutes'),
	(5,'Five minutes'),
	(6,'Six minutes'),
	(7,'Seven minutes'),
	(8,'Eight minutes'),
	(9,'Nine minutes'),
	(10,'Ten minutes'),
	)

	interview_duration = models.IntegerField(
	choices=INTERVIEW_DURATION,
	blank=False,
	default=4,
	help_text='How long do you want every interaction to be? (per student)',
	)
	REST_DURATION = (
	(1,'One minutes'),
	(2,'Two minutes'),
	(3,'Three minutes'),
	(4,'Four minutes'),
	)

	rest_duration = models.IntegerField(
	choices=REST_DURATION,
	blank=False,
	default=2,
	help_text='How long do you need to rest between interactions?',
	)
	date = models.DateField(null=True, blank=True)
	time_start = models.TimeField(null=True, blank=True)
	time_end = models.TimeField(null=True, blank=True)
	university = models.CharField(max_length=100)
	booth_name = models.CharField(max_length=200)
	career_fair = models.ForeignKey(Career_Fair, on_delete=models.SET_NULL, null=True, blank=True)
	# View detail button would display above information as well as other information they want to include

class Dictionary_Booth(models.Model):
    career_booth = models.OneToOneField(Career_Booth, on_delete=models.CASCADE, null=True, blank=True)

class KeyVal(models.Model):
	container = models.ForeignKey(Dictionary_Booth, db_index=True, on_delete=models.CASCADE, null=True)
	key       = models.CharField(max_length=240, db_index=True)
	end   = models.CharField(max_length=240, blank=True)
	#value     = models.OneToOneField(CustomUser, db_index=True, on_delete=models.SET_NULL, null=True)
	value = models.ForeignKey(CustomUser, db_index=True, on_delete=models.SET_NULL, null=True)

source/career_fair/forms.py
from django import forms
from django.forms import ValidationError
from django.conf import settings
from .models import Career_Booth
from django.utils import timezone
from django.db.models import Q

from django.forms import ModelForm

from dal import autocomplete

import datetime
from django.forms.widgets import SelectDateWidget
from event.widgets import SelectTimeWidget

def uni_list():
    return settings.UNIV_LIST

class CreateBoothForm(forms.ModelForm):
	class Meta:
		model = Career_Booth
		fields = ('interview_duration', 'rest_duration','date', 'time_start', 'time_end', 'university','booth_name')
	years_to_display = range(datetime.datetime.now().year,
	datetime.datetime.now().year + 2)
	date = forms.DateField(
		widget=SelectDateWidget(years=years_to_display), 
		required = True,
		initial = datetime.datetime.now(),
		)
	time_start = forms.TimeField(
		widget=SelectTimeWidget(),
		required = True,
		initial = datetime.time(9,00),
		)
	time_end = forms.TimeField(
		widget=SelectTimeWidget(),
		required = True,
		initial = datetime.time(12,00),
		)
	university = autocomplete.Select2ListCreateChoiceField(
		choice_list=uni_list(),
		required=True,
		widget=autocomplete.ListSelect2(url='accounts:uni-autocomplete')
		#initial = self.user.university
		)
	booth_name = forms.CharField(
		required=False,label='Booth Name',
		max_length=100,
		help_text='Optional. The name is only used on your calendar.'
		)




	# @property
 #    def booth_check(self):
 #    	request = self.request
	# 	recruiter = request.user
	# 	recruiter_object = Recruiter.objects.filter(user = request.user)[0]
	# 	# Check for career fairs, if none exist, create one
	# 	week_number = booth.date.strftime("%V")
	# 	year = booth.date.year
	# 	firstdate, lastdate =  getDateRangeFromWeek(year,week_number)
	# 	booth.company = recruiter.company
 #        return ['email_or_username', 'password']

source/career_fair/views.py
from django.shortcuts import render
from .models import Career_Fair, Career_Booth, Dictionary_Booth, KeyVal
from event.models import Event
from accounts.models import Student, Recruiter
from django.views.generic import TemplateView, CreateView
from .forms import uni_list, CreateBoothForm
from time import strftime
from dal import autocomplete
from django.contrib import messages
from django.http import HttpResponseRedirect
import time
import datetime
from django.shortcuts import get_object_or_404, get_list_or_404
from django.forms import ValidationError
from zoomus import ZoomClient
from datetime import timedelta
from django.utils import timezone

def available(request, slot_id):
	new_slot = KeyVal.objects.filter(pk = slot_id)[0]
	user = request.user
	date = new_slot.container.career_booth.date
	# First check conflicts with career fair
	current_slots = KeyVal.objects.filter(value = user)
	print(current_slots)
	for keyval in current_slots:
		print(keyval.container)
		if(keyval.container.career_booth.date == date):
			# Check the time
			time_to_add = datetime.datetime.strptime(new_slot.key, '%H:%M')
			start_seconds_to_add = time_to_add.hour * 3600 + time_to_add.minute * 60
			duration_to_add = (1 + new_slot.container.career_booth.interview_duration) * 60
			total_add = start_seconds_to_add + duration_to_add
			time_pot_conflict = datetime.datetime.strptime(keyval.key, '%H:%M')
			start_seconds_pot_conflict = time_pot_conflict.hour * 3600 + time_pot_conflict.minute * 60
			duration_pot_conflict = (1 + keyval.container.career_booth.interview_duration) * 60
			total_conflict = start_seconds_pot_conflict + duration_pot_conflict
			# First case is if our new event starts during the potential conflicted event
			# Second case is if our new event ends during the potential conflicted event
			if((start_seconds_to_add >= start_seconds_pot_conflict and 
				start_seconds_to_add <= total_conflict) or
				(total_add >= start_seconds_pot_conflict and total_add <= total_conflict)):
				return False
	# Next, check conflicts with infosessions
	current_infosessions = Event.objects.filter(rsvp_list__in = [user], date = date)
	for infosession in current_infosessions:
		# Check the time
		new_start = datetime.datetime.strptime(new_slot.key, '%H:%M')
		new_start_seconds = new_start.hour * 3600 + new_start.minute * 60
		duration_to_add = (1 + new_slot.container.career_booth.interview_duration) * 60
		new_end_seconds = new_start_seconds + duration_to_add

		old_start_seconds = infosession.start_time.hour * 3600 + infosession.start_time.minute * 60
		old_end_seconds = infosession.end_time.hour * 3600 + infosession.end_time.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds)):
			return False
	return True

def recruiter_available(request, booth):
	new_booth = booth
	recruiter = request.user
	date = new_booth.date
	new_start_time = new_booth.time_start
	new_end_time = new_booth.time_end
	# First check conflicts with booths
	current_booths = Career_Booth.objects.filter(recruiter = recruiter, date = date)
	for booth in current_booths:
		# Check the time
		# new_start = datetime.datetime.strptime(new_start_time, '%H:%M')
		new_start_seconds = new_start_time.hour * 3600 + new_start_time.minute * 60
		# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
		new_end_seconds = new_end_time.hour * 3600 + new_end_time.minute * 60

		# old_start = datetime.datetime.strptime(booth.time_start, '%H:%M')
		old_start_seconds = booth.time_start.hour * 3600 + booth.time_start.minute * 60
		# old_end = datetime.datetime.strptime(booth.time_end, '%H:%M')
		old_end_seconds = booth.time_end.hour * 3600 + booth.time_end.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds)):
			return False
	# Next, check conflicts with infosessions
	current_infosessions = Event.objects.filter(main_recruiter = recruiter, date = date)
	for infosession in current_infosessions:
		# Check the time
		# new_start = datetime.datetime.strptime(new_start_time, '%H:%M')
		new_start_seconds = new_start_time.hour * 3600 + new_start_time.minute * 60
		# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
		new_end_seconds = new_end_time.hour * 3600 + new_end_time.minute * 60

		# old_start = datetime.datetime.strptime(booth.time_start, '%H:%M')
		old_start_seconds = infosession.start_time.hour * 3600 + infosession.start_time.minute * 60
		# old_end = datetime.datetime.strptime(booth.time_end, '%H:%M')
		old_end_seconds = infosession.end_time.hour * 3600 + infosession.end_time.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds)):
			return False
	return True

class AutocompleteUni(autocomplete.Select2ListView):
    def get_list(self):
        return uni_list()

def signup(request, slot_id):
	slot = get_object_or_404(KeyVal, pk=slot_id)
	signup_dictionary = get_list_or_404(KeyVal, container=get_object_or_404(Dictionary_Booth,
																			career_booth=slot.container.career_booth))
	user = request.user

	if slot.value != None:
		messages.error(request, ("Sorry! Someone already signed up for this slot."))
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	for time in signup_dictionary:
		if time.value == user:
			messages.error(request, ("Sorry! You've already signed up for this booth."))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	if not available(request, slot_id):
		messages.error(request, ("Sorry! It looks like you have a scheduling conflict with another booth. Please note that there must be at least a minute buffer between interviews."))
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	slot.value = user
	slot.save()
	messages.success(request, ('You have successfully signed up for this time slot!'))
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def change(request, slot_id):
	slot = get_object_or_404(KeyVal, pk=slot_id)
	signup_dictionary = get_list_or_404(KeyVal, container=get_object_or_404(Dictionary_Booth,
																			career_booth=slot.container.career_booth))
	user = request.user

	if slot.value != None:
		messages.error(request, ("Sorry! Someone already signed up for this slot."))
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	if not available(request, slot_id):
		messages.error(request, ("Sorry! It looks like you have a scheduling conflict with another booth. Please note that there must be at least a minute buffer between interviews."))
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	for time in signup_dictionary:
		if time.value == user:
			time.value = None
			slot.value = user
			time.save()
			slot.save()
			messages.success(request, ('You have successfully signed up for this time slot!'))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def remove(request, slot_id):
	slot = get_object_or_404(KeyVal, pk=slot_id)
	user = request.user

	if slot.value == user:
		slot.value = None
		messages.success(request, ("You've successfully unregistered from this time slot!"))
	else:
		messages.error(request, ("Sorry! You don't appear to be in this time slot!"))
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	slot.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def getDateRangeFromWeek(p_year,p_week):

    firstdayofweek = datetime.datetime.strptime(f'{p_year}-W{int(p_week )- 1}-1', "%Y-W%W-%w").date()
    lastdayofweek = firstdayofweek + datetime.timedelta(days=6.9)
    return firstdayofweek, lastdayofweek

def time_slots(start_time, end_time, interview_duration, rest_duration):
	student_duration = interview_duration + rest_duration
	t = start_time
	while t <= (datetime.datetime.combine(datetime.date.today(), end_time)
					- datetime.timedelta(minutes=interview_duration)).time():
		yield t.strftime('%H:%M')
		t = (datetime.datetime.combine(datetime.date.today(), t) +
			datetime.timedelta(minutes=student_duration)).time()

class CreateBooth(CreateView):
	template_name = 'career_fair/create_booth.html'
	model = Career_Booth
	form_class = CreateBoothForm
	def save(self, *args, **kwargs):
		self.absolute_url = self.get_absolute_url()
		super(event, self).save(*args, **kwargs)
	def form_valid(self, form):
		booth = form.save()
		request = self.request
		booth.recruiter = request.user
		recruiter = Recruiter.objects.filter(user = request.user)[0]
		# Check for scheduling conflicts
		if not recruiter_available(request, booth):
			booth.delete()
			messages.error(request, ('You have a scheduling conflict with another event that you have created previously.'))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		# Check for career fairs, if none exist, create one
		week_number = booth.date.strftime("%V")
		year = booth.date.year
		firstdate, lastdate =  getDateRangeFromWeek(year,week_number)
		booth.company = recruiter.company
		existing_fairs = Career_Fair.objects.filter(firstdate=firstdate, lastdate = lastdate, university = booth.university)
		if(len(existing_fairs) == 0):
			fair = Career_Fair.objects.create(university = booth.university,
			                     firstdate = firstdate,

source/career_fair/templates/career_fair/booth_creation_error.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
    You cannot create a booth for those dates, as one already exists for your company.
{% endblock %}

source/career_fair/templates/career_fair/career_fair_dashboard.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% if request.user.is_authenticated %}

      <div class="headline">
        <h1>Upcoming Career Fairs

        {% if request.user.is_recruiter %}
          <a href="{% url 'career_fair:create-booth'%}" class="btn btn-outline-dark btn-sm">
            <i class="fa fa-plus" aria-hidden="true"></i> Create Booth</a>
        {% endif %}

        </h1> 
      </div>

        {% if career_list %}
             <ul>
                <div class="container">
                {% for event in career_list %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->
              
                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{event.university}}</h5>
                      <p class="list-group-item">{{event.firstdate}} to {{event.lastdate}}</p>
                  </div>

                  <div class="card-body">
                      <a href="{% url 'career_fair:detail' event.id %}" class="btn btn-info"> View Booths</a>

                  </div>
            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% else %}
          <p>There are no event in the library.</p>
        {% endif %}     


    <h1>Past Career Fairs</h1>

        {% if past_career_list %}
             <ul>
                <div class="container">
                {% for event in past_career_list %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->

                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{event.university}}</h5>
                      <p class="list-group-item">{{event.firstdate}} to {{event.lastdate}}</p>
                  </div>

                  <div class="card-body">
                      <a href="{% url 'career_fair:detail' event.id %}" class="btn btn-info"> View Booths</a>

                  </div>
            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% else %}
          <p>There are no event in the library.</p>
        {% endif %}

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

source/career_fair/templates/career_fair/create_booth.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
    	{% if request.user.is_recruiter %}
    		  <div class="row">
			    <div class="col-md-8 col-sm-10 col-12">
			      <h2>Create your booth</h2>
			      <form method="post" novalidate>
			        {% csrf_token %}
			        <input type="hidden" name="next" value="{{ next }}">
			        {{ form|crispy }}
					</script>
			        <button type="submit" class="btn btn-success">Submit</button>
			      </form>
			    </div>
			  </div>
    	{% else %}
    		You are not a recruiter, thus, cannot create an event
    	{% endif %}
    {% else %}
    	You are not authenticated. Please validate your email to create an event.
    {% endif %}

{% endblock %}


{% block footer %}

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}
<script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>

{% endblock %}

source/career_fair/templates/career_fair/delete_booth_confirmation.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

<h1> Are you sure you want to delete your career booth? </h1>
<p> 
    <button class="btn btn-success" onclick="location.href='{% url 'career_fair:delete_booth' booth_id %}'">Yes</button>
   <script>
        function goBack()
        {
            window.history.back()
        }
    </script>
    <input class="btn btn-primary" type="button" value="No" onclick="goBack()">
</p>

{% endblock %}

source/career_fair/templates/career_fair/view_booth_details.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <p>University: {{ booth.university }} </p>    
    <p>Company: {{ booth.company }} </p>
    <p>Time: {{ booth.date }} from {{ booth.time_start }} to {{ booth.time_end }}</p>
    <p>Interview Duration: {{ booth.interview_duration }} minutes
    </p> 

        {% for slot in signup_list %}
            <p>Time Start: {{ slot.key }}
                {% if request.user.is_student %}
                    {% if slot == signedup_slot %}
                        <button class="btn btn-danger" onclick="location.href='{% url 'career_fair:remove' slot.id %}'">Remove!</button>
                    {% elif slot.value == None %}
                        {% if signedup_slot %}
                            <button class="btn btn-warning" onclick="location.href='{% url 'career_fair:change' slot.id %}'">Change!</button>
                        {% else %}
                            <button class="btn btn-success" onclick="location.href='{% url 'career_fair:signup' slot.id %}'">Sign Up!</button>
                        {% endif %}
                    {% endif %}
                {% elif request.user.is_recruiter %}
                    {{ slot.value }}
                {% endif %}
            </p>
        {% endfor %}
        
        {% if request.user.is_recruiter %}
            <button class="btn btn-danger" onclick="location.href='{% url 'career_fair:delete_booth_confirmation' booth.id %}'">Delete Event!</button> 
        {% endif %}

        <script>
            function goBack()
            {
                window.history.back()
            }
        </script>
        <input class="btn btn-primary" type="button" value="<<Back" onclick="goBack()">
{% endblock %}

source/career_fair/templates/career_fair/view_booths.html
{% extends 'layouts/default/page.html' %}
{% load i18n %}
{% load my_extras %}

{% block content %}
    <p>University: {{ event.university }}</p>
    <p>Start Date: {{ event.firstdate }}</p>
    <p>End Date: {{ event.lastdate }}</p>

    {% if user_booths %}
    <h1>Your Booths</h1>
             <ul>
                <div class="container">
                {% for booth in user_booths %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->
                  {% if booth.booth_name %}
                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{booth.booth_name}}</h5>
                      <p class="card-text">{{booth.recruiter}}</p>
                  {% else %}
                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{booth.company}}</h5>
                      <p class="card-text">{{booth.recruiter}}</p>
                  {% endif %}
                      

                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{booth.date}} from {{booth.time_start}} to {{booth.time_end}}</li>
                      </ul>
                  </div>

                  <div class="card-body">
                      <script language="javascript" type="text/javascript">
                        <!--
                            function popitup(url) {
                                newwindow=window.open(url,'{{title}}','height=600,width=450');
                                if (window.focus) {newwindow.focus()}
                                return false;
                            }

                        // -->
                       </script>
                            <a href="{% url 'career_fair:booth_detail' event.id booth.company %}" class="btn btn-info" onclick="return popitup('details/{{ booth.company }}')">
                                {% trans 'View Details' %} </a>
                            {% if request.user.is_student and zoom_time|get_item:booth %}
                                <a class="btn btn-success" href= {{booth.join_zoom_url}} target="_blank" role="button">Join Meeting</a>
                            {% elif request.user.is_recruiter and zoom_time|get_item:booth %}
                                <a class="btn btn-success" href= {{booth.start_zoom_url}} target="_blank" role="button">Start Meeting</a>
                            {% endif %}
                  </div>

            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% endif %}
    {% if other_booths %}
    {% if request.user.is_student %}
    <h1>Available Booths</h1>
    {% elif request.user.is_recruiter %}
    <h1>Other Booths</h1>
    {% endif %}
             <ul>
                <div class="container">
                {% for booth in other_booths %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->

                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{booth.company}}</h5>
                      <p class="card-text">{{booth.recruiter}}</p>


                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{booth.date}} from {{booth.time_start}} to {{booth.time_end}}</li>
                      </ul>
                  </div>

                  <div class="card-body">
                    {% if request.user.is_student %}
                      <script language="javascript" type="text/javascript">
                        <!--
                            function popitup(url) {
                                newwindow=window.open(url,'{{title}}','height=600,width=450');
                                if (window.focus) {newwindow.focus()}
                                return false;
                            }

                        // -->
                       </script>
                            <a href="{% url 'career_fair:booth_detail' event.id booth.company %}" class="btn btn-info" onclick="return popitup('details/{{ booth.company }}')">
                                {% trans 'View Details' %} </a>
                    {% endif %}
                  </div>

            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% endif %}
    <script>
        function goBack()
        {
            window.history.back()
        }
    </script>
    <input class="btn btn-primary" type="button" value="<<Back" onclick="goBack()">

    
{% endblock %}