source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('event/', include('event.urls')),
    path('profile/', include('user_profile.urls')),
    path('calendar/', include('calendars.urls')),
    path('career_fair/', include('career_fair.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/event/urls.py
from django.urls import path
from django.conf.urls import url, include

from .views import (
    ViewEvent,
    EventList,
    MyEventList,
    CreateEvent,
    EventDashboard,
    detail,
    rsvp,
    un_rsvp,
    delete_event,
    PastEventList
    )

app_name = "event"


urlpatterns = [
    path('', EventDashboard.as_view(), name='event_dashboard'),
    path('event_list/', EventList.as_view(), name='event_list'),
    path('my_event_list/', MyEventList.as_view(), name='my_event_list'),
    url(r'^rsvp/(?P<event_id>[0-9]+)/$', rsvp, name='rsvp'),
    url(r'^un_rsvp/(?P<event_id>[0-9]+)/$', un_rsvp, name='un_rsvp'),
    url(r'^delete_event/(?P<event_id>[0-9]+)/$', delete_event, name='delete_event'),
    path('create_event', CreateEvent.as_view(), name ='create_event'),
    url(r'^(?P<event_id>[0-9]+)/$', detail, name='detail'),
    path('past_event/', PastEventList.as_view(), name='past_event'),
]

source/event/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from accounts.models import Recruiter, CustomUser, Student

class Event(models.Model):
    """Model representing a event."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    main_recruiter = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank = True)
    # additional_recruiters = models.ManyToManyField(Recruiter,related_name = 'otherRecruiters')
    # company = models.ForeignKey('Company', on_delete=models.SET_NULL, null=True)
    
    date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null = True, blank = True)
    end_time = models.TimeField(null = True, blank = True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the event')
    join_zoom_url = models.CharField(max_length=1000)
    start_zoom_url = models.CharField(max_length=1000)

    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
     
    # typE = models.ManyToManyField(Type, help_text='Select a type for the event')
    absolute_url = models.CharField(max_length=400, blank=True, editable=False)

    rsvp_list = models.ManyToManyField(CustomUser, related_name = 'rsvp_list')

    rsvp_capacity = models.IntegerField(default=0)
    space_open = models.IntegerField(default=-1)


    def __str__(self):
        """String for representing the Model object."""
        return f'{self.title}, {self.date}, {self.main_recruiter}' 
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this event."""  
        return reverse('event-detail', args=[str(self.id)])

source/event/forms.py
from django import forms
from django.forms import ValidationError
from django.conf import settings
from .models import Event
from django.utils import timezone
from django.db.models import Q

from django.forms import ModelForm

from django.db import transaction
from dal import autocomplete

import datetime
from django.forms.widgets import SelectDateWidget
from .widgets import SelectTimeWidget

class CreateEventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = ('title', 'date', 'start_time', 'end_time','summary', 'rsvp_capacity')
	years_to_display = range(datetime.datetime.now().year,
	datetime.datetime.now().year + 2)
	date = forms.DateField(
		widget=SelectDateWidget(years=years_to_display),
		initial = datetime.datetime.now(),
	)
	start_time = forms.TimeField(
        widget=SelectTimeWidget(),
		initial = datetime.time(9,00),
    )

	end_time = forms.TimeField(
        widget=SelectTimeWidget(),
		initial = datetime.time(12,00),
    )
	
	rsvp_capacity = forms.IntegerField(label='Maximum Number of Students to Attend')

source/event/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings
from django.views.generic import TemplateView, CreateView
from .models import Event
from accounts.models import Recruiter
from career_fair.models import KeyVal, Career_Booth
from .forms import CreateEventForm
import json
from zoomus import ZoomClient
from django.utils.dateparse import parse_datetime
from django.http import HttpResponseRedirect
from datetime import datetime, timedelta
from django.utils import timezone

def student_available(request, event_id):
	new_infosession = Event.objects.filter(pk = event_id)[0]
	user = request.user
	date = new_infosession.date
	# First check conflicts with career fair
	current_slots = KeyVal.objects.filter(value = user)
	for keyval in current_slots:
		if(keyval.container.career_booth.date == date):
			# Check the time
			new_start_seconds = new_infosession.start_time.hour * 3600 + new_infosession.start_time.minute * 60
			# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
			new_end_seconds = new_infosession.end_time.hour * 3600 + new_infosession.end_time.minute * 60

			time_pot_conflict = datetime.strptime(keyval.key, '%H:%M')
			start_seconds_pot_conflict = time_pot_conflict.hour * 3600 + time_pot_conflict.minute * 60
			duration_pot_conflict = (1 + keyval.container.career_booth.interview_duration) * 60
			total_conflict = start_seconds_pot_conflict + duration_pot_conflict
			# First case is if our new event starts during the potential conflicted event
			# Second case is if our new event ends during the potential conflicted event
			if((new_start_seconds >= start_seconds_pot_conflict and 
				new_start_seconds <= total_conflict) or
				(new_end_seconds >= start_seconds_pot_conflict and new_end_seconds <= total_conflict)):
				return False
	# Next, check conflicts with infosessions
	current_infosessions = Event.objects.filter(rsvp_list__in = [user], date = date)
	for infosession in current_infosessions:
		# Check the time
		new_start_seconds = new_infosession.start_time.hour * 3600 + new_infosession.start_time.minute * 60
		# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
		new_end_seconds = new_infosession.end_time.hour * 3600 + new_infosession.end_time.minute * 60


		old_start_seconds = infosession.start_time.hour * 3600 + infosession.start_time.minute * 60
		old_end_seconds = infosession.end_time.hour * 3600 + infosession.end_time.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds)):
			return False
	return True

def recruiter_available(request, infosession):
	new_infosession = infosession
	recruiter = request.user
	date = new_infosession.date
	new_start_time = new_infosession.start_time
	new_end_time = new_infosession.end_time
	# First check conflicts with booths
	current_booths = Career_Booth.objects.filter(recruiter = recruiter, date = date)
	for booth in current_booths:
		# Check the time
		# new_start = datetime.datetime.strptime(new_start_time, '%H:%M')
		new_start_seconds = new_start_time.hour * 3600 + new_start_time.minute * 60
		# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
		new_end_seconds = new_end_time.hour * 3600 + new_end_time.minute * 60

		# old_start = datetime.datetime.strptime(booth.time_start, '%H:%M')
		old_start_seconds = booth.time_start.hour * 3600 + booth.time_start.minute * 60
		# old_end = datetime.datetime.strptime(booth.time_end, '%H:%M')
		old_end_seconds = booth.time_end.hour * 3600 + booth.time_end.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds) or
			(new_start_seconds < old_start_seconds and new_end_seconds > old_end_seconds)):
			return False
	# Next, check conflicts with infosessions
	current_infosessions = Event.objects.filter(main_recruiter = recruiter, date = date)
	for infosession in current_infosessions:
		# Check the time
		# new_start = datetime.datetime.strptime(new_start_time, '%H:%M')
		new_start_seconds = new_start_time.hour * 3600 + new_start_time.minute * 60
		# new_end = datetime.datetime.strptime(new_end_time, '%H:%M')
		new_end_seconds = new_end_time.hour * 3600 + new_end_time.minute * 60

		# old_start = datetime.datetime.strptime(booth.time_start, '%H:%M')
		old_start_seconds = infosession.start_time.hour * 3600 + infosession.start_time.minute * 60
		# old_end = datetime.datetime.strptime(booth.time_end, '%H:%M')
		old_end_seconds = infosession.end_time.hour * 3600 + infosession.end_time.minute * 60
		# First case is if our new event starts during the potential conflicted event
		# Second case is if our new event ends during the potential conflicted event
		# Third case is if our new event overlaps both beginning and end the potential conflicted events same at line 99
		if((new_start_seconds >= old_start_seconds and 
			new_start_seconds <= old_end_seconds) or
			(new_end_seconds >= old_start_seconds and new_end_seconds <= old_end_seconds) or
			(new_start_seconds < old_start_seconds and new_end_seconds > old_end_seconds)):
			return False
	return True

def detail(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	rsvp = True
	if(event in Event.objects.filter(rsvp_list__in = [request.user])):
		rsvp = False
	past = False
	if(event.date < datetime.now().date()):
		past = True
	return render(request, 'event/view_event.html', {'event': event, 'rsvp_bool': rsvp, 'past':past})

def rsvp(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	user = request.user
	if event.space_open != 0:
		if not student_available(request, event_id):
			messages.error(request, ("Sorry! It looks like you have a scheduling conflict with another event. Please note that there must be at least a minute buffer around events."))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		event.rsvp_list.add(user)
		event.space_open -= 1
		event.save()
		messages.success(request, _('You have successfully rsvpd for the event'))
	else:
		messages.error(request, _('Sorry! All spaces have been filled,'))
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def un_rsvp(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	user = request.user
	event.rsvp_list.remove(user)
	event.space_open += 1
	event.save()
	messages.success(request, _('You have successfully unregistered to the event'))
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def delete_event(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	event.delete()
	messages.success(request, _('You have successfully deleted your event!'))
	return HttpResponseRedirect('/event')

class ViewEvent(TemplateView):
    template_name = 'event/view_event.html'

class EventDashboard(TemplateView):
	template_name = 'event/event_dashboard.html'
	def get_context_data(self, **kwargs):
		request = self.request
		context = super(EventDashboard, self).get_context_data(**kwargs)
		not_in_event_list, counter, zoom_time = [], 0, {}
		now = timezone.make_aware(datetime.now(),timezone.get_default_timezone())
		if(request.user.is_recruiter):
			context['event_list'] = Event.objects.filter(
				main_recruiter = request.user, date__gte = datetime.now() - timedelta(days=1)).order_by('date')[:3]
		elif(request.user.is_student):
			context['event_list'] = Event.objects.filter(
				rsvp_list__in = [request.user], date__gte = datetime.now() - timedelta(days=1)).order_by('date')[:3]
		for i in context['event_list']:
			now_seconds = now.hour * 3600 + now.minute * 60
			info_start_seconds = i.start_time.hour * 3600 + i.start_time.minute * 60
			info_end_seconds = i.end_time.hour * 3600 + i.end_time.minute * 60
			if str(i.date) == now.strftime('%Y-%m-%d'):
				if info_start_seconds <= (now_seconds + 300) and now_seconds < info_end_seconds:
					zoom_time[i] = True
				else:
					zoom_time[i] = False
			else:
				zoom_time[i] = False
		context['zoom_time'] = zoom_time

		for i in Event.objects.filter(date__gte = datetime.now() - timedelta(days=1)).order_by('date'):
			if counter == 6:
				break
			if i not in context['event_list']:
				counter += 1
				not_in_event_list.append(i)

		context['all_events'] = not_in_event_list

		if (request.user.is_recruiter):
			context['past_event_list'] = Event.objects.filter(
				main_recruiter=request.user, date__lte=datetime.now() - timedelta(days=1)).order_by('date')[:3]
		elif (request.user.is_student):
			context['past_event_list'] = Event.objects.filter(

source/event/templates/event/create_event.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
    	{% if request.user.is_recruiter %}
    		  <div class="row">
			    <div class="col-md-8 col-sm-10 col-12">
			      <h2>Create your Infosession</h2>
			      <form method="post" novalidate>
			        {% csrf_token %}
			        <input type="hidden" name="next" value="{{ next }}">
			        {{ form|crispy }}
					</script>
			        <button type="submit" class="btn btn-success">Submit</button>
			      </form>
			    </div>
			  </div>
    	{% else %}
    		You are not a recruiter, thus, cannot create an Infosession
    	{% endif %}
    {% else %}
    	You are not authenticated. Please validate your email to create an Infosession.
    {% endif %}

{% endblock %}

source/event/templates/event/event_dashboard.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}
{% load my_extras %}

{% block content %}

    {% if request.user.is_authenticated %}

      <div class="headline">
        <h1>My Infosessions
        <button class="btn btn-outline-dark btn-sm" onclick="location.href='{% url 'event:my_event_list' %}'">
            {% if request.user.is_recruiter %}
                View All of Your Infosessions
            {% else %}
                View all of Your RSVP Infosessions
            {% endif %}
        </button>

        {% if request.user.is_recruiter %}
        <button class="btn btn-outline-dark btn-sm" onclick="location.href='{% url 'event:create_event' %}'">
          <i class="fa fa-plus" aria-hidden="true"></i> Create Event
        </button>
        {% endif %}

        </h1> 
      </div>

        {% if event_list %}
             <ul>
                <div class="container">
                {% for event in event_list %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->
              
                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{event.title}}</h5>
                      <p class="card-text">{{event.summary}}</p>
                      

                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{event.main_recruiter}}</li>
                        <li class="list-group-item">{{event.date}}: from {{event.start_time}} to {{event.end_time}}</li>
                        <li class="list-group-item"> Spaces Open:
                            {% if event.rsvp_capacity != 0 %}
                            {{event.space_open}}
                            {% else %}
                            No Limit!
                            {% endif %}</li>
                      </ul>
                  </div>

                  <div class="card-body">
                      <a href="{% url 'event:detail' event.id %}" class="btn btn-info"> See Details</a> {{event.company}}
                      {% if request.user.is_student and not zoom_time|get_item:event %}
                        <a href="{% url 'event:un_rsvp' event.id %}" class="btn btn-success"> Unregister </a>
                      {% endif %}
                      {% if request.user.is_student and zoom_time|get_item:event %}
                          <a class="btn btn-success" href= {{event.join_zoom_url}} target="_blank" role="button">Join Meeting</a>
                      {% elif request.user.is_recruiter and zoom_time|get_item:event %}
                          <a class="btn btn-success" href= {{event.start_zoom_url}} target="_blank" role="button">Start Meeting</a>
                      {% endif %}
                  </div>

            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% else %}
          <p>There are no Infosessions in the library.</p>
        {% endif %}     
        

      {% if request.user.is_student %}
          <div class="headline">
            <h1>Infosession Dashboard
            <button class="btn btn-warning" onclick="location.href='{% url 'event:event_list' %}'">View All Infosessions</button> 
            </h1> 
          </div>

            {% if all_events %}
          <!-- </div class="card-group"> -->
            <ul>
                <div class="container">
                {% for event in all_events %}
                    {% if forloop.counter0|divisibleby:3 %}
                    <div class = "row">
                     {% endif %}
                      <div class="col-sm">

                      <div class="card border-info mb-3" style="max-width: 20rem;">
                        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                        <!-- <div class="card-header">Header</div> -->
                  
                        <div class="card-body text-dark">
                            <h5 class="card-title bg-info text-white ">{{event.title}}</h5>
                            <p class="card-text">{{event.summary}}</p>
                            

                            <ul class="list-group list-group-flush">
                              <li class="list-group-item">{{event.main_recruiter}}</li>
                              <li class="list-group-item">{{event.date}}: from {{event.start_time}} to {{event.end_time}}</li>
                              <li class="list-group-item"> Spaces Open:
                                  {% if event.rsvp_capacity != 0 %}
                                  {{event.space_open}}
                                  {% else %}
                                  No Limit!
                                  {% endif %}</li>
                            </ul>
                        </div> 
                        
                        <div class="card-body">
                            <a href="{% url 'event:detail' event.id %}" class="btn btn-info"> See Details</a> {{event.company}}
                            {% if event.space_open != 0 %}
                              <a href="{% url 'event:rsvp' event.id %}" class="btn btn-success"> RSVP </a>
                            {% endif %}
                        </div>

                      </div>
                      </div>

                    {% if forloop.counter|divisibleby:3 %}
                    </div>
                    {% endif %}
              
                {% endfor %}
                
                <div class="col-sm"> </div>
                </div>
                </div>
            </ul>
        
            {% else %}
              <p>There are no event in the library.</p>
            {% endif %} 
          </ul>  
      {% endif %}

     <div class="headline">
        <h1>My Past Infosessions
        <button class="btn btn-outline-dark btn-sm" onclick="location.href='{% url 'event:past_event' %}'">
            View all Past Infosessions
        </button>

        </h1>
      </div>

        {% if past_event_list %}
             <ul>
                <div class="container">
                {% for event in past_event_list %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


                <div class="card border-info mb-3" style="max-width: 20rem;">
                  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                  <!-- <div class="card-header">Header</div> -->

                    <div class="card-body text-dark">
                        <h5 class="card-title bg-info text-white ">{{event.title}}</h5>
                        <p class="card-text">{{event.summary}}</p>


                        <ul class="list-group list-group-flush">
                          <li class="list-group-item">{{event.main_recruiter}}</li>
                          <li class="list-group-item">{{event.date}}: from {{event.start_time}} to {{event.end_time}}</li>
                          <li class="list-group-item"> Spaces Open:
                              {% if event.rsvp_capacity != 0 %}
                              {{event.space_open}}
                              {% else %}
                              No Limit!
                              {% endif %}</li>
                        </ul>
                    </div>

                    <div class="card-body">
                        <a href="{% url 'event:detail' event.id %}" class="btn btn-info"> See Details</a> {{event.company}}
                    </div>

              </div>
              </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% else %}
          <p>There are no Infosessions in the library.</p>
        {% endif %}

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

source/event/templates/event/event_list.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% if request.user.is_authenticated %}

          <h1>Infosession Dashboard</h1>
            {% if all_events %}
          <!-- </div class="card-group"> -->
           <ul>
                <div class="container">
                {% for event in all_events %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">

                  <div class="card border-info mb-3" style="max-width: 20rem;">
                    <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                    <!-- <div class="card-header">Header</div> -->

                      <div class="card-body text-dark">
                          <h5 class="card-title bg-info text-white ">{{event.title}}</h5>
                          <p class="card-text">{{event.summary}}</p>


                          <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{event.main_recruiter}}</li>
                            <li class="list-group-item">{{event.date}} at {{event.time}}</li>
                            <li class="list-group-item"> Spaces Open:
                                {% if event.rsvp_capacity != 0 %}
                                {{event.space_open}}
                                {% else %}
                                No Limit!
                                {% endif %}</li>
                          </ul>

                      </div>

                      <div class="card-body">
                          <a href="{% url 'event:detail' event.id %}" class="btn btn-info"> See Details</a> {{event.company}}
                          <a href="{% url 'event:rsvp' event.id %}" class="btn btn-success"> RSVP </a>
                      </div>

                  </div>
                  </div>

                  <!-- <li>
                    <a href="{% url 'event:detail' event.id %}">{{ event.title }}</a> {{event.company}}
                  </li> -->

                    {% if forloop.counter|divisibleby:3 %}
                    </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>

                </div>
                </div>
            </ul>

            {% else %}
              <p>There are no Infosessions in the library.</p>
            {% endif %}
          </ul>

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

source/event/templates/event/my_event_list.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}
{% load my_extras %}
{% block content %}

    {% if request.user.is_authenticated %}
      
      <div class="headline">
        <h1>My Infosessions
        <!-- <button class="btn btn-success" onclick="location.href='{% url 'event:my_event_list' %}'">View All RSVP Events</button>  -->
        </h1> 
      </div>

        {% if event_list %}
             <ul>
                <div class="container">
                {% for event in event_list %}
                    {% if forloop.counter0|divisibleby:3 %}
                        <div class = "row">
                     {% endif %}
                        <div class="col-sm">


              <div class="card border-info mb-3" style="max-width: 20rem;">
                <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                <!-- <div class="card-header">Header</div> -->

                  <div class="card-body text-dark">
                      <h5 class="card-title bg-info text-white ">{{event.title}}</h5>
                      <p class="card-text">{{event.summary}}</p>


                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{event.main_recruiter}}</li>
                        <li class="list-group-item">{{event.date}}: from {{event.start_time}} to {{event.end_time}}</li>
                        <li class="list-group-item"> Spaces Open:
                            {% if event.rsvp_capacity != 0 %}
                            {{event.space_open}}
                            {% else %}
                            No Limit!
                            {% endif %}</li>
                      </ul>
                  </div>

                  <div class="card-body">
                      <a href="{% url 'event:detail' event.id %}" class="btn btn-info"> See Details</a> {{event.company}}
                      {% if request.user.is_student and not zoom_time|get_item:event %}
                        <a href="{% url 'event:un_rsvp' event.id %}" class="btn btn-success"> Unregister </a>
                      {% endif %}
                      {% if request.user.is_student and zoom_time|get_item:event %}
                          <a class="btn btn-success" href= {{event.join_zoom_url}} target="_blank" role="button">Join Meeting</a>
                      {% elif request.user.is_recruiter and zoom_time|get_item:event %}
                          <a class="btn btn-success" href= {{event.start_zoom_url}} target="_blank" role="button">Start Meeting</a>
                      {% endif %}
                  </div>

            </div>
            </div>
                    {% if forloop.counter|divisibleby:3 %}
              </div>
                    {% endif %}
                {% endfor %}
                    <div class="col-sm"> </div>
          </ul>
        {% else %}
          <p>There are no Infosessions in the library.</p>
        {% endif %}

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

source/event/templates/event/view_event.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
    <p>Title: {{ event.title }}</p>
    <p>Recruiter: {{ event.main_recruiter }}</p>
    <p>Summary: {{ event.summary }}</p>
    <p>Date: {{ event.date }}</p>
    <p>Time: From {{ event.start_time }} to {{ event.end_time }}</p>

    {% if event in past_event_list %}
        {% trans 'This Infosession has already occurred.' %}
    {% else %}
        {% if request.user.is_student %}
            {% if rsvp_bool %}
                <button class="btn btn-success" onclick="location.href='{% url 'event:rsvp' event.id%}'"> RSVP</button>
                <a class="btn btn-info" href= {{event.join_zoom_url}} target="_blank" role="button">Join Meeting</a>
            {% else %}
                <a href="{% url 'event:un_rsvp' event.id %}" class="btn btn-success"> Unregister </a>
            {% endif %}
        {% elif request.user.is_recruiter %}
            <a class="btn btn-info" href= {{event.start_zoom_url}} target="_blank" role="button">Start Meeting</a>
            <button class="btn btn-warning" onclick="location.href='{% url 'event:delete_event' event.id%}'"> Delete Event</button>
        {% else %}
            {% trans 'You are a guest.' %}
        {% endif %}
    {% endif %}
    <script>
        function goBack()
        {
            window.history.back()
        }
    </script>
    <input class="btn btn-primary" type="button" value="<<Back" onclick="goBack()">
    
{% endblock %}